name: Check App Updates
on:
  schedule:
    - cron: '0 * * * *' # Controlla ogni ora esatta
  workflow_dispatch: # Permette di avviarlo manualmente per test

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permette a GitHub di salvare i file delle versioni
    steps:
      - name: Checkout codice
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Installa librerie
        run: pip install requests

      - name: Esegui controllo versioni
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py

      - name: Salva modifiche
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add version_*.txt
          git commit -m "Aggiornamento log versioni" || exit 0
          git push
